# Generates app/data/wajibat/decisionTrees.ts (Phase 4b helpers). Needs .cache/_build/wdata.json
# from a first dataset dump (build.py runs this between the two dumps).
import os, sys
from helpers_dsl import ts
import tree_sd
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "app", "data", "wajibat", "decisionTrees.ts"))

trees = [tree_sd.build()]
if os.path.exists(os.path.join(HERE, "tree_kd.py")):
    import tree_kd; trees.append(tree_kd.build())
if os.path.exists(os.path.join(HERE, "tree_w.py")):
    import tree_w; trees += tree_w.build()
data = [t.build() for t in trees]
import helpers_dsl
if helpers_dsl.ERRS:
    print(len(helpers_dsl.ERRS), "authoring errors:"); [print(" ", e) for e in helpers_dsl.ERRS]; sys.exit(1)
body = ts(data)
open(OUT, "w", encoding="utf-8", newline="\n").write(
    "// GENERATED by scripts/wajibat/gen_helpers.py -- do not edit by hand (decision R9).\n"
    "import type { DecisionTree } from \"./types\";\n\n"
    f"export const DECISION_TREES: DecisionTree[] = {body};\n")
print("trees:", [(d["id"], len(d["nodes"])) for d in data])
