# Generates app/data/wajibat/rulingIndex.ts: one line per ruling (id, topic, subject, and the marja' of a
# supplementary Q&A entry). It lets the hub search and the topic links work without loading any
# category chunk. Reads the dataset dump, so build.py runs it after the last dump.
import json, os, sys
from paths import DATA, TMP
data = json.load(open(os.path.join(TMP, "wdata.json"), encoding="utf-8"))
LF = chr(10)
rows = []
for r in data["rulings"]:
    row = {"id": r["id"], "topicId": r["topicId"], "subject": r["subject"]}
    if r.get("supplementary"):
        row["supplementaryMarja"] = r["supplementary"]["marjaId"]
    rows.append(row)
body = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
body = body.replace("},{", "}," + LF + "  {").replace("[{", "[" + LF + "  {").replace("}]", "}" + LF + "]")
open(os.path.join(DATA, "rulingIndex.ts"), "w", encoding="utf-8", newline=LF).write(
    "// GENERATED by scripts/wajibat/gen_index.py: do not edit by hand (decision R9)." + LF
    + "// One line per ruling, so search and links need no category chunk." + LF + LF
    + "export interface RulingIndexEntry {" + LF
    + "  id: string;" + LF + "  topicId: string;" + LF + "  subject: { en: string; ur?: string };" + LF
    + "  /** Set for a marja's supplementary Q&A entry (shown to his followers only). */" + LF
    + '  supplementaryMarja?: "sistani" | "khamenei" | "makarem";' + LF + "}" + LF + LF
    + "export const WAJIBAT_RULING_INDEX: RulingIndexEntry[] = " + body + ";" + LF)
print("ruling index:", len(rows))
