# Generates app/data/wajibat/decisionTrees.ts (Phase 4b helpers). Needs .cache/_build/wdata.json
# from a first dataset dump (build.py runs this between the two dumps).
import os, sys
from helpers_dsl import ts
import tree_sd
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "app", "data", "wajibat", "decisionTrees.ts"))

trees = [tree_sd.build()]
if os.path.exists(os.path.join(HERE, "tree_kd.py")):
    import tree_kd; trees.append(tree_kd.build())
if os.path.exists(os.path.join(HERE, "tree_w.py")):
    import tree_w; trees += tree_w.build()
data = [t.build() for t in trees]
import helpers_dsl
if helpers_dsl.ERRS:
    print(len(helpers_dsl.ERRS), "authoring errors:"); [print(" ", e) for e in helpers_dsl.ERRS]; sys.exit(1)
# One file per category, so each category's data chunk carries only its own helpers (Phase 5 follow-up);
# decisionTrees.ts aggregates them for the tests and scripts that read the whole dataset.
TOPIC_CAT = {"doubts": "salat", "wudu": "taharat"}
LF = chr(10)
DIR = os.path.dirname(OUT)
os.makedirs(os.path.join(DIR, "decisionTrees"), exist_ok=True)
CATS = ["salat", "taharat"]
for cat in CATS:
    part = [d for d in data if TOPIC_CAT[d["topicId"]] == cat]
    open(os.path.join(DIR, "decisionTrees", cat + ".ts"), "w", encoding="utf-8", newline=LF).write(
        "// GENERATED by scripts/wajibat/gen_helpers.py -- do not edit by hand (decision R9)." + LF
        + 'import type { DecisionTree } from "../types";' + LF + LF
        + f"export const {cat.upper()}_TREES: DecisionTree[] = {ts(part)};" + LF)
open(OUT, "w", encoding="utf-8", newline=LF).write(
    "// GENERATED by scripts/wajibat/gen_helpers.py -- do not edit by hand (decision R9)." + LF
    + "// Aggregate of the per-category helper files, for the tests and scripts that read the whole dataset." + LF
    + 'import type { DecisionTree } from "./types";' + LF
    + "".join(f'import {{ {c.upper()}_TREES }} from "./decisionTrees/{c}";' + LF for c in CATS) + LF
    + "export const DECISION_TREES: DecisionTree[] = [" + ", ".join(f"...{c.upper()}_TREES" for c in CATS) + "];" + LF)
print("trees:", [(d["id"], len(d["nodes"])) for d in data])
