import sys,re,html
s=open(sys.argv[1],encoding='utf-8',errors='replace').read()
s=re.sub(r'(?is)<(script|style|nav|header|footer)[^>]*>.*?</\1>','',s)
s=re.sub(r'(?i)<br\s*/?>|</p>|</h\d>|</div>|</li>','\n',s)
s=re.sub(r'<[^>]+>','',s)
s=html.unescape(s)
s=re.sub(r'[ \t\r]+',' ',s)
s=re.sub(r'\n\s*\n+','\n',s)
sys.stdout.reconfigure(encoding='utf-8')
print(s.strip())
