// GENERATED by scripts/wajibat/gen_helpers.py -- do not edit by hand (decision R9).
// Aggregate of the per-category helper files, for the tests and scripts that read the whole dataset.
import type { DecisionTree } from "./types";
import { SALAT_TREES } from "./decisionTrees/salat";
import { TAHARAT_TREES } from "./decisionTrees/taharat";

export const DECISION_TREES: DecisionTree[] = [...SALAT_TREES, ...TAHARAT_TREES];
