// GENERATED by scripts/wajibat/gen_helpers.py -- do not edit by hand (decision R9).
import type { DecisionTree } from "../types";

export const TAHARAT_TREES: DecisionTree[] = [
  {
    id: "sistaniwudu",
    topicId: "wudu",
    marjaId: "sistani",
    title: {
      en: "Wuḍūʾ: doubts and what invalidates it (Sayyid al-Sistani)"
    },
    intro: {
      kind: "explanation",
      text: {
        en: "Answer a few questions about your situation and this page will show the passage of Sayyid al-Sistani's Islamic Laws that applies. It never gives a ruling of its own: every answer is his own wording. If a question doesn't fit your case, choose \"I'm not sure\"."
      }
    },
    rootId: "swroot",
    risala: {
      book: "Islamic Laws (4th edition)",
      location: "Issues 298–305 and 322 (doubts about wuḍūʾ; things that invalidate wuḍūʾ)",
      url: "https://www.sistani.org/english/book/48/2157/"
    },
    nodes: [
      {
        id: "swroot",
        question: {
          kind: "explanation",
          text: {
            en: "What is your question about?"
          }
        },
        options: [
          {
            id: "swrooto1",
            label: {
              en: "I am not sure whether I performed wuḍūʾ at all"
            },
            nextId: "swperf",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "doubts whether he has performed wuḍūʾ or not"
              }
            ]
          },
          {
            id: "swrooto2",
            label: {
              en: "I performed wuḍūʾ and am not sure whether it has become void"
            },
            nextId: "swvoid",
            basedOn: [
              {
                rulingId: "wududoubtvoid",
                phrase: "doubts whether his wuḍūʾ has become void or not"
              }
            ]
          },
          {
            id: "swrooto3",
            label: {
              en: "I know I performed wuḍūʾ and that I did something that invalidates it, but not which came first"
            },
            nextId: "swbefore",
            basedOn: [
              {
                rulingId: "wuduorderunknown",
                phrase: "does not know which one was first"
              }
            ]
          },
          {
            id: "swrooto4",
            label: {
              en: "I found out afterwards that my wuḍūʾ was invalid"
            },
            nextId: "swlate",
            basedOn: [
              {
                rulingId: "wuduunaware",
                phrase: "learns that his wuḍūʾ or ghusl was invalid"
              },
              {
                rulingId: "wuduvoidtime",
                phrase: "his wuḍūʾ has become void but doubts"
              }
            ]
          },
          {
            id: "swrooto5",
            label: {
              en: "I want to know whether something invalidates wuḍūʾ"
            },
            nextId: "swinv",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "Seven things invalidate wuḍūʾ"
              }
            ]
          },
          {
            id: "swrooto6",
            label: {
              en: "I doubt very often about the acts and conditions of wuḍūʾ"
            },
            nextId: "swexcess",
            basedOn: [
              {
                rulingId: "wuduexcessive",
                phrase: "frequently doubts about the acts of wuḍūʾ"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swperf",
        question: {
          kind: "explanation",
          text: {
            en: "When did the doubt arise?"
          }
        },
        options: [
          {
            id: "swperfo1",
            label: {
              en: "Before the prayer"
            },
            nextId: "swp1",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "he must [deem that he has not and] perform wuḍūʾ"
              }
            ]
          },
          {
            id: "swperfo2",
            label: {
              en: "During the prayer"
            },
            nextId: "swp2",
            basedOn: [
              {
                rulingId: "wududoubtduring",
                phrase: "doubts during prayers whether or not he had performed wuḍūʾ"
              }
            ]
          },
          {
            id: "swperfo3",
            label: {
              en: "After the prayer"
            },
            nextId: "swp3",
            basedOn: [
              {
                rulingId: "wududoubtafterprayer",
                phrase: "doubts after prayers whether he had performed wuḍūʾ or not"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swp1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtperformed",
              text: "If a person doubts whether he has performed wuḍūʾ or not, he must [deem that he has not and] perform wuḍūʾ.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "perform wuḍūʾ"
          ]
        }
      },
      {
        id: "swp2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtduring",
              text: "If a person doubts during prayers whether or not he had performed wuḍūʾ, then based on obligatory precaution, he must perform wuḍūʾ and perform the prayer again.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "he must perform wuḍūʾ and perform the prayer again"
          ]
        }
      },
      {
        id: "swp3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtafterprayer",
              text: "If a person doubts after prayers whether he had performed wuḍūʾ or not, his prayers are valid but he must perform wuḍūʾ for subsequent prayers.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "his prayers are valid but he must perform wuḍūʾ for subsequent prayers"
          ]
        }
      },
      {
        id: "swvoid",
        question: {
          kind: "explanation",
          text: {
            en: "Is this your situation: after urinating you did not perform istibrāʾ, then performed wuḍūʾ, and afterwards some fluid came out that you do not know to be urine or something else?"
          }
        },
        options: [
          {
            id: "swvoido1",
            label: {
              en: "No"
            },
            nextId: "swv1",
            basedOn: [
              {
                rulingId: "wududoubtvoid",
                phrase: "he must treat it as still being valid"
              }
            ]
          },
          {
            id: "swvoido2",
            label: {
              en: "Yes"
            },
            nextId: "swv2",
            basedOn: [
              {
                rulingId: "wududoubtvoid",
                phrase: "his wuḍūʾ is void"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swv1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtvoid",
              text: "If someone doubts whether his wuḍūʾ has become void or not, he must treat it as still being valid.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "he must treat it as still being valid"
          ]
        }
      },
      {
        id: "swv2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtvoid",
              text: "However, if after urinating one does not perform istibrāʾ and performs wuḍūʾ, and after performing wuḍūʾ some fluid is discharged about which he does not know if it is urine or something else, his wuḍūʾ is void.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "his wuḍūʾ is void"
          ],
          seeRulingIds: [
            "istibradoubt"
          ]
        }
      },
      {
        id: "swbefore",
        question: {
          kind: "explanation",
          text: {
            en: "When did the doubt arise?"
          }
        },
        options: [
          {
            id: "swbeforeo1",
            label: {
              en: "Before the prayer"
            },
            nextId: "swb1",
            basedOn: [
              {
                rulingId: "wuduorderunknown",
                phrase: "in the event that he has this doubt before prayers, he must perform wuḍūʾ for those prayers"
              }
            ]
          },
          {
            id: "swbeforeo2",
            label: {
              en: "During the prayer"
            },
            nextId: "swb2",
            basedOn: [
              {
                rulingId: "wuduorderunknown",
                phrase: "If he has this doubt during prayers, he must break his prayer and perform wuḍūʾ"
              }
            ]
          },
          {
            id: "swbeforeo3",
            label: {
              en: "After the prayer"
            },
            nextId: "swb3",
            basedOn: [
              {
                rulingId: "wuduorderunknown",
                phrase: "if he has this doubt after prayers, the prayer he performed is valid"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swb1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduorderunknown",
              text: "If someone knows he has performed wuḍūʾ and also knows that he has done something that invalidates wuḍūʾ – for example, he has urinated – but he does not know which one was first [i.e. he does not know whether he performed wuḍūʾ and then urinated, for example, or he urinated and then performed wuḍūʾ], then in the event that he has this doubt before prayers, he must perform wuḍūʾ for those prayers.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "he must perform wuḍūʾ for those prayers"
          ]
        }
      },
      {
        id: "swb2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduorderunknown",
              text: "If someone knows he has performed wuḍūʾ and also knows that he has done something that invalidates wuḍūʾ – for example, he has urinated",
              lang: "en"
            },
            {
              rulingId: "wuduorderunknown",
              text: "If he has this doubt during prayers, he must break his prayer and perform wuḍūʾ.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "he must break his prayer and perform wuḍūʾ"
          ]
        }
      },
      {
        id: "swb3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduorderunknown",
              text: "And if he has this doubt after prayers, the prayer he performed is valid but he must perform wuḍūʾ for subsequent prayers.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "the prayer he performed is valid but he must perform wuḍūʾ for subsequent prayers"
          ]
        }
      },
      {
        id: "swlate",
        question: {
          kind: "explanation",
          text: {
            en: "What did you find out, and when?"
          }
        },
        options: [
          {
            id: "swlateo1",
            label: {
              en: "During or after the prayer I learned that my wuḍūʾ was invalid (or that I prayed without it)"
            },
            nextId: "swl1",
            basedOn: [
              {
                rulingId: "wuduunaware",
                phrase: "he must perform the prayer again with wuḍūʾ or ghusl"
              }
            ]
          },
          {
            id: "swlateo2",
            label: {
              en: "After the prayer I realised my wuḍūʾ had become void, but I don't know whether this happened before or after the prayer"
            },
            nextId: "swl2",
            basedOn: [
              {
                rulingId: "wuduvoidtime",
                phrase: "doubts whether his wuḍūʾ became void before or after prayers"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swl1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduunaware",
              text: "If during or after prayers one learns that his wuḍūʾ or ghusl was invalid, or that he started performing prayers without wuḍūʾ or ghusl, he must perform the prayer again with wuḍūʾ or ghusl; and if the time for the prayer has expired, he must make it up.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "he must perform the prayer again with wuḍūʾ or ghusl"
          ]
        }
      },
      {
        id: "swl2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduvoidtime",
              text: "If a person realises after prayers that his wuḍūʾ has become void but doubts whether his wuḍūʾ became void before or after prayers, the prayers performed by him are valid.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "the prayers performed by him are valid"
          ]
        }
      },
      {
        id: "swinv",
        question: {
          kind: "explanation",
          text: {
            en: "What happened?"
          }
        },
        options: [
          {
            id: "swinvo1",
            label: {
              en: "I passed urine, stool or wind"
            },
            nextId: "swi1",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "urinating"
              },
              {
                rulingId: "wuduinvalidators",
                phrase: "defecating"
              }
            ]
          },
          {
            id: "swinvo2",
            label: {
              en: "I slept"
            },
            nextId: "swi2",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "sleeping, which means that simultaneously one’s eyes do not see and one’s ears do not hear"
              }
            ]
          },
          {
            id: "swinvo3",
            label: {
              en: "I lost my mind (insanity, intoxication, unconsciousness)"
            },
            nextId: "swi3",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "things that cause one to lose his mind"
              }
            ]
          },
          {
            id: "swinvo4",
            label: {
              en: "A woman's istiḥāḍah, or janābah, or something else that requires ghusl"
            },
            nextId: "swi4",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "istiḥāḍah of a woman"
              }
            ]
          },
          {
            id: "swinvo5",
            label: {
              en: "Some fluid came out"
            },
            nextId: "swfluid",
            basedOn: [
              {
                rulingId: "dischargesmadhi",
                phrase: "fluid that sometimes comes out"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swi1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "Seven things invalidate wuḍūʾ:",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "1. urinating; and apparently included in the ruling of urinating is the similar moisture that comes out after urinating and before performing istibrāʾ;",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "2. defecating;",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "3. passing wind of the stomach and the intestine from the anus;",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "Seven things invalidate wuḍūʾ"
          ]
        }
      },
      {
        id: "swi2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "Seven things invalidate wuḍūʾ:",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "4. sleeping, which means that simultaneously one’s eyes do not see and one’s ears do not hear; however, if one’s eyes do not see but his ears hear, his wuḍūʾ does not become invalid;",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "his wuḍūʾ does not become invalid"
          ]
        }
      },
      {
        id: "swi3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "Seven things invalidate wuḍūʾ:",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "5. things that cause one to lose his mind, such as insanity, intoxication, and unconsciousness;",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "things that cause one to lose his mind"
          ]
        }
      },
      {
        id: "swi4",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "Seven things invalidate wuḍūʾ:",
              lang: "en"
            },
            {
              rulingId: "wuduinvalidators",
              text: "6. istiḥāḍah of a woman, which will be discussed later;\n7. janābah; and based on recommended precaution, all things for which one must perform ghusl.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "janābah"
          ]
        }
      },
      {
        id: "swfluid",
        question: {
          kind: "explanation",
          text: {
            en: "Which of these describes the fluid?"
          }
        },
        options: [
          {
            id: "swfluido1",
            label: {
              en: "A woman who sees fluid and doubts whether it is urine"
            },
            nextId: "swf1",
            basedOn: [
              {
                rulingId: "istibrawomen",
                phrase: "if a woman sees fluid and doubts whether it is urine or not"
              }
            ]
          },
          {
            id: "swfluido2",
            label: {
              en: "A man: the fluid called madhī, wadhī or wadī (or I did istibrāʾ and doubt whether it is urine or one of these)"
            },
            nextId: "swf2",
            basedOn: [
              {
                rulingId: "dischargesmadhi",
                phrase: "called ‘madhī’"
              }
            ]
          },
          {
            id: "swfluido3",
            label: {
              en: "A man: I did not perform istibrāʾ (or doubt that I did), and fluid came out that I don't know to be pure"
            },
            nextId: "swf3",
            basedOn: [
              {
                rulingId: "istibradoubt",
                phrase: "If a man doubts whether he has performed istibrāʾ or not"
              }
            ]
          },
          {
            id: "swfluido4",
            label: {
              en: "A man: I doubt whether the istibrāʾ I performed was correct, and fluid came out"
            },
            nextId: "swf4",
            basedOn: [
              {
                rulingId: "istibradoubt",
                phrase: "if a man doubts whether the istibrāʾ he performed was correct or not"
              }
            ]
          }
        ],
        notSureId: "swnotsure"
      },
      {
        id: "swf1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "istibrawomen",
              text: "There is no istibrāʾ for women after urinating; if a woman sees fluid and doubts whether it is urine or not, it is pure and it does not invalidate her wuḍūʾ or ghusl.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "it does not invalidate her wuḍūʾ"
          ]
        }
      },
      {
        id: "swf2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "dischargesmadhi",
              text: "The fluid that sometimes comes out of the penis due to sexual arousal, called ‘madhī’, is pure. The fluid that sometimes comes out after the ejaculation of semen, called ‘wadhī’, is also pure. As for fluid that sometimes comes out after urinating and which is called ‘wadī’, it is pure if it has not come into contact with urine. Furthermore, in the event that a man performs istibrāʾ after urinating and then fluid comes out and he doubts whether it is urine or one of these three fluids, it is pure.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "is pure"
          ],
          seeRulingIds: [
            "wuduinvalidators"
          ]
        }
      },
      {
        id: "swf3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "istibradoubt",
              text: "If a man doubts whether he has performed istibrāʾ or not and fluid comes out and he does not know whether it is pure or not, it is impure; and in the event that he performed wuḍūʾ, his wuḍūʾ becomes void (bāṭil).",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "it is impure",
            "his wuḍūʾ becomes void (bāṭil)"
          ]
        }
      },
      {
        id: "swf4",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "istibradoubt",
              text: "However, if a man doubts whether the istibrāʾ he performed was correct or not and fluid comes out and he is unsure whether it is pure or not, it is pure and it does not invalidate his wuḍūʾ either.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "it does not invalidate his wuḍūʾ either"
          ]
        }
      },
      {
        id: "swexcess",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduexcessive",
              text: "Someone who frequently doubts about the acts of wuḍūʾ and its conditions – such as the water being pure and not being usurped – must not heed his doubts.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "must not heed his doubts"
          ]
        }
      },
      {
        id: "swnotsure",
        outcome: {
          kind: "refer",
          reason: {
            kind: "explanation",
            text: {
              en: "You said you are not sure. The page does not guess: please read the passage in Sayyid al-Sistani's Islamic Laws, or ask his office, so that the answer rests on what actually happened."
            }
          }
        }
      }
    ]
  },
  {
    id: "khameneiwudu",
    topicId: "wudu",
    marjaId: "khamenei",
    title: {
      en: "Wuḍūʾ: doubts and what invalidates it (Ayatollah Khamenei)"
    },
    intro: {
      kind: "explanation",
      text: {
        en: "Answer a few questions about your situation and this page will show Ayatollah Khamenei's own wording. Most of his rulings on this come from the official Urdu translation of his practical treatise (Aḥkām-e Āmūzishī, lesson 16); no official English translation of that treatise exists, so those answers are shown in Urdu, exactly as published, with a label, and the page never translates them. English readers can check them in his risala or ask his office. If a question doesn't fit your case, choose \"I'm not sure\"."
      }
    },
    rootId: "kwroot",
    risala: {
      book: "Aḥkām-e Āmūzishī (official Urdu translation of Risāla-yi Āmūzishī)",
      location: "Lesson 16 (wuḍūʾ) and Practical Laws of Islam Q 90–92, 122",
      url: "https://www.leader.ir/ur/book/201/1?sn=32120"
    },
    nodes: [
      {
        id: "kwroot",
        question: {
          kind: "explanation",
          text: {
            en: "What is your question about?"
          }
        },
        options: [
          {
            id: "kwrooto1",
            label: {
              en: "I am not sure whether I performed wuḍūʾ at all"
            },
            nextId: "kwperf",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "اصل وضو میں شک"
              }
            ]
          },
          {
            id: "kwrooto2",
            label: {
              en: "I performed wuḍūʾ and am not sure whether it has become void"
            },
            nextId: "kw1",
            basedOn: [
              {
                rulingId: "wududoubtvoid",
                phrase: "doubt concerning state of purity after the performance of wuḍū’"
              }
            ]
          },
          {
            id: "kwrooto3",
            label: {
              en: "I found out afterwards that my wuḍūʾ was invalid"
            },
            nextId: "kw2",
            basedOn: [
              {
                rulingId: "wuduunaware",
                phrase: "وضو باطل ہونے کے بارے میں"
              }
            ]
          },
          {
            id: "kwrooto4",
            label: {
              en: "I want to know whether something invalidates wuḍūʾ"
            },
            nextId: "kwinv",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "پیشاب نکلنا"
              }
            ]
          },
          {
            id: "kwrooto5",
            label: {
              en: "I doubt very often about the acts and conditions of wuḍūʾ"
            },
            nextId: "kw3",
            basedOn: [
              {
                rulingId: "wuduexcessive",
                phrase: "زیادہ شک کرتا ہے"
              }
            ]
          }
        ],
        notSureId: "kwnotsure"
      },
      {
        id: "kwperf",
        question: {
          kind: "explanation",
          text: {
            en: "When did the doubt arise?"
          }
        },
        options: [
          {
            id: "kwperfo1",
            label: {
              en: "Before the prayer"
            },
            nextId: "kwp1",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "نماز سے پہلے ہوتو وضو کرنا چاہئے"
              }
            ]
          },
          {
            id: "kwperfo2",
            label: {
              en: "During the prayer"
            },
            nextId: "kwp2",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "نماز کے دوران ہوتو اس کی نماز باطل ہے"
              }
            ]
          },
          {
            id: "kwperfo3",
            label: {
              en: "After the prayer"
            },
            nextId: "kwp3",
            basedOn: [
              {
                rulingId: "wududoubtperformed",
                phrase: "نماز کے بعد (شک کرے"
              }
            ]
          }
        ],
        notSureId: "kwnotsure"
      },
      {
        id: "kwp1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtperformed",
              text: "اصل وضو میں شک (یعنی شک کرے کہ وضو کیا ہے یا نہیں)",
              lang: "ur"
            },
            {
              rulingId: "wududoubtperformed",
              text: "نماز سے پہلے ہوتو وضو کرنا چاہئے",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "وضو کرنا چاہئے"
          ]
        }
      },
      {
        id: "kwp2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtperformed",
              text: "اصل وضو میں شک (یعنی شک کرے کہ وضو کیا ہے یا نہیں)",
              lang: "ur"
            },
            {
              rulingId: "wududoubtperformed",
              text: "نماز کے دوران ہوتو اس کی نماز باطل ہے اور دوبارہ وضو کرکے دوبارہ نماز پڑھے",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "اس کی نماز باطل ہے"
          ]
        }
      },
      {
        id: "kwp3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtperformed",
              text: "اصل وضو میں شک (یعنی شک کرے کہ وضو کیا ہے یا نہیں)",
              lang: "ur"
            },
            {
              rulingId: "wududoubtperformed",
              text: "نماز کے بعد (شک کرے کہ وضو کے ساتھ نماز پڑھی ہے یا نہیں) تو جو نماز پڑھی ہے وہ صحیح ہے لیکن بعد والی نمازوں کے لئے وضو کرنا چاہئے",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "جو نماز پڑھی ہے وہ صحیح ہے"
          ]
        }
      },
      {
        id: "kw1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wududoubtvoid",
              text: "No attention should be paid to doubt concerning state of purity after the performance of wuḍū’. And it is permissible for one to offer prayer and read the Noble Qur’an, etc. as long as one is not certain that his wuḍū’ has been invalidated.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "No attention should be paid to doubt concerning state of purity after the performance of wuḍū’"
          ]
        }
      },
      {
        id: "kw2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduunaware",
              text: "1۔ جو شخص اپنا وضو باطل ہونے کے بارے میں جاہل ہو اور وضو کے بعد متوجہ ہوجائے تو واجب ہے کہ وضو سے مشروط اعمال کے لئے دوبارہ وضو کرے اور باطل وضو کے ساتھ نماز پڑھی ہے تو اس کو بھی دوبارہ پڑھنا واجب ہے۔",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "دوبارہ وضو کرے"
          ]
        }
      },
      {
        id: "kw3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduexcessive",
              text: "2۔ جو شخص وضو کے افعال اور شرائط مثلا پانی کا پاک ہونا اور غصبی نہ ہونا میں زیادہ شک کرتا ہے اس کو چاہئے کہ اپنے شک پر اعتناء نہ کرے",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "اپنے شک پر اعتناء نہ کرے"
          ]
        }
      },
      {
        id: "kwinv",
        question: {
          kind: "explanation",
          text: {
            en: "What happened?"
          }
        },
        options: [
          {
            id: "kwinvo1",
            label: {
              en: "I passed urine, stool or wind"
            },
            nextId: "kwi1",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "پیشاب نکلنا"
              }
            ]
          },
          {
            id: "kwinvo2",
            label: {
              en: "I slept"
            },
            nextId: "kwi2",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "نیند آنا"
              }
            ]
          },
          {
            id: "kwinvo3",
            label: {
              en: "I lost my mind (insanity, intoxication, unconsciousness)"
            },
            nextId: "kwi3",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "بے ہوشی"
              }
            ]
          },
          {
            id: "kwinvo4",
            label: {
              en: "A woman's istiḥāḍah, or janābah, or something else that requires ghusl"
            },
            nextId: "kwi4",
            basedOn: [
              {
                rulingId: "wuduinvalidators",
                phrase: "استحاضہ"
              }
            ]
          },
          {
            id: "kwinvo5",
            label: {
              en: "Some fluid came out (madhī, wadhī, wadī, or a doubtful fluid after urinating)"
            },
            nextId: "kwfluid",
            basedOn: [
              {
                rulingId: "dischargesmadhi",
                phrase: "pure and do not invalidate wuḍū’"
              }
            ]
          }
        ],
        notSureId: "kwnotsure"
      },
      {
        id: "kwi1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "1۔ پیشاب نکلنا\n2۔ پاخانہ نکلنا\n3۔ معدہ یا انتڑیوں سے ہوا نکلنا",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "پیشاب نکلنا"
          ]
        }
      },
      {
        id: "kwi2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "4۔ اس طرح نیند آنا کہ آنکھ نہ دیکھے اور کان نہ سنے",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "نیند"
          ]
        }
      },
      {
        id: "kwi3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "5۔ وہ چیزیں جو عقل کو زائل کرتی ہیں مثلا دیوانگی، مستی اور بے ہوشی",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "بے ہوشی"
          ]
        }
      },
      {
        id: "kwi4",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "wuduinvalidators",
              text: "6۔ عورتوں کا استحاضہ\n7۔ ہر وہ چیز جو غسل کا باعث بنتی ہے مثلا جنابت، حیض اور مس میت",
              lang: "ur"
            }
          ],
          verdictPhrases: [
            "استحاضہ"
          ]
        }
      },
      {
        id: "kwfluid",
        question: {
          kind: "explanation",
          text: {
            en: "Which describes the fluid?"
          }
        },
        options: [
          {
            id: "kwfluido1",
            label: {
              en: "The fluid called madhī, wadhī or wadī"
            },
            nextId: "kwf1",
            basedOn: [
              {
                rulingId: "dischargesmadhi",
                phrase: "All of them are pure and do not invalidate wuḍū’"
              }
            ]
          },
          {
            id: "kwfluido2",
            label: {
              en: "Fluid that came out after istibrāʾ, and I doubt whether it is urine"
            },
            nextId: "kwf2",
            basedOn: [
              {
                rulingId: "istibradoubt",
                phrase: "after doing istibrā’, about which one doubts whether it is urine"
              }
            ]
          },
          {
            id: "kwfluido3",
            label: {
              en: "Fluid that came out after urinating when I did not do istibrāʾ, and I doubt what it is"
            },
            nextId: "kwf3",
            basedOn: [
              {
                rulingId: "istibra",
                phrase: "if one does not do istibrā’ and a doubtful liquid comes out, it will be ruled as urine"
              }
            ]
          }
        ],
        notSureId: "kwnotsure"
      },
      {
        id: "kwf1",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "dischargesmadhi",
              text: "The wetness that comes out occasionally after the discharge of semen is called ‘wadhi’ That which comes out occasionally after urinating is called ‘wadi’, and that which comes out after foreplay is called ‘madhi’. All of them are pure and do not invalidate wuḍū’.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "All of them are pure and do not invalidate wuḍū’"
          ]
        }
      },
      {
        id: "kwf2",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "istibradoubt",
              text: "The wetness that comes out after doing istibrā’, about which one doubts whether it is urine or not, is not considered urine. It is to be considered pure, and it is not obligatory to do any investigation in this case.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "is not considered urine"
          ]
        }
      },
      {
        id: "kwf3",
        outcome: {
          kind: "ruling",
          quotes: [
            {
              rulingId: "istibra",
              text: "Doing istibrā’ is not obligatory. Furthermore, it is not allowed if it causes a considerable harm. However, after urination if one does not do istibrā’ and a doubtful liquid comes out, it will be ruled as urine.",
              lang: "en"
            }
          ],
          verdictPhrases: [
            "it will be ruled as urine"
          ]
        }
      },
      {
        id: "kwnotsure",
        outcome: {
          kind: "refer",
          reason: {
            kind: "explanation",
            text: {
              en: "You said you are not sure. The page does not guess: please read Ayatollah Khamenei's treatise (the Urdu Aḥkām-e Āmūzishī, or the Persian Risāla-yi Āmūzishī), or ask his office, so that the answer rests on what actually happened."
            }
          }
        }
      }
    ]
  }
];
